### ISSUE TITLE
Could not load file or assembly 'Microsoft.WindowsAzure.Configuration

### ISSUE THREAD

**Issue by JunyanLin** [harouny/NLog.Extensions.AzureTableStorage#30]
I got this error. 
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.WindowsAzure.Configuration, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Microsoft.WindowsAzure.Configuration, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at NLog.Extensions.AzureTableStorage.ConfigManager.GetStorageAccountConnectionString()
   at NLog.Extensions.AzureTableStorage.AzureTableStorageTarget.InitializeTarget()
   at NLog.Targets.Target.Initialize(LoggingConfiguration configuration)

**Comment by JunyanLin** [comment]
nvm, I updated the Azure configuration package and it's good now.
